services:
  backend:
    restart: always
    volumes: []
    deploy:
      resources:
        limits:
          cpus: "2"
          memory: 4G
        reservations:
          cpus: "0.5"
          memory: 1G

  dashboard:
    restart: always
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: 256M

  db:
    restart: always
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: 1G
