"""add rbac models and org_id fks

Revision ID: 6f11ca848bb2
Revises: 7a1c8c2f4d1b
Create Date: 2026-07-02 21:35:55.096238

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6f11ca848bb2'
down_revision: Union[str, Sequence[str], None] = '7a1c8c2f4d1b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organizations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('contact_email', sa.String(length=200), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('classes',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('org_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('grade', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('org_id', sa.String(length=36), nullable=False),
    sa.Column('email', sa.String(length=200), nullable=False),
    sa.Column('password_hash', sa.String(length=200), nullable=False),
    sa.Column('display_name', sa.String(length=100), nullable=False),
    sa.Column('role', sa.Enum('super_admin', 'org_admin', 'teacher', 'parent', name='user_role'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('teacher_classes',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('teacher_id', sa.String(length=36), nullable=False),
    sa.Column('class_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['class_id'], ['classes.id'], ),
    sa.ForeignKeyConstraint(['teacher_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('teacher_id', 'class_id', name='uq_teacher_class')
    )
    op.create_table('parent_children',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('parent_id', sa.String(length=36), nullable=False),
    sa.Column('child_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['child_id'], ['children.id'], ),
    sa.ForeignKeyConstraint(['parent_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('parent_id', 'child_id', name='uq_parent_child')
    )
    op.add_column('analysis_results', sa.Column('child_id', sa.String(length=36), nullable=True))
    op.create_foreign_key(None, 'analysis_results', 'children', ['child_id'], ['id'])
    op.add_column('children', sa.Column('org_id', sa.String(length=36), nullable=False))
    op.add_column('children', sa.Column('class_id', sa.String(length=36), nullable=True))
    op.add_column('children', sa.Column('added_by', sa.String(length=36), nullable=True))
    op.create_foreign_key(None, 'children', 'classes', ['class_id'], ['id'])
    op.create_foreign_key(None, 'children', 'users', ['added_by'], ['id'])
    op.create_foreign_key(None, 'children', 'organizations', ['org_id'], ['id'])
    op.add_column('devices', sa.Column('org_id', sa.String(length=36), nullable=False))
    op.create_foreign_key(None, 'devices', 'organizations', ['org_id'], ['id'])
    op.add_column('reports', sa.Column('child_id', sa.String(length=36), nullable=True))
    op.add_column('reports', sa.Column('generated_by', sa.String(length=36), nullable=True))
    op.create_foreign_key(None, 'reports', 'children', ['child_id'], ['id'])
    op.create_foreign_key(None, 'reports', 'users', ['generated_by'], ['id'])
    op.add_column('sessions', sa.Column('org_id', sa.String(length=36), nullable=False))
    op.add_column('sessions', sa.Column('class_id', sa.String(length=36), nullable=True))
    op.add_column('sessions', sa.Column('teacher_id', sa.String(length=36), nullable=True))
    op.add_column('sessions', sa.Column('title', sa.String(length=200), nullable=True))
    op.create_foreign_key(None, 'sessions', 'organizations', ['org_id'], ['id'])
    op.create_foreign_key(None, 'sessions', 'users', ['teacher_id'], ['id'])
    op.create_foreign_key(None, 'sessions', 'classes', ['class_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'sessions', type_='foreignkey')
    op.drop_constraint(None, 'sessions', type_='foreignkey')
    op.drop_constraint(None, 'sessions', type_='foreignkey')
    op.drop_column('sessions', 'title')
    op.drop_column('sessions', 'teacher_id')
    op.drop_column('sessions', 'class_id')
    op.drop_column('sessions', 'org_id')
    op.drop_constraint(None, 'reports', type_='foreignkey')
    op.drop_constraint(None, 'reports', type_='foreignkey')
    op.drop_column('reports', 'generated_by')
    op.drop_column('reports', 'child_id')
    op.drop_constraint(None, 'devices', type_='foreignkey')
    op.drop_column('devices', 'org_id')
    op.drop_constraint(None, 'children', type_='foreignkey')
    op.drop_constraint(None, 'children', type_='foreignkey')
    op.drop_constraint(None, 'children', type_='foreignkey')
    op.drop_column('children', 'added_by')
    op.drop_column('children', 'class_id')
    op.drop_column('children', 'org_id')
    op.drop_constraint(None, 'analysis_results', type_='foreignkey')
    op.drop_column('analysis_results', 'child_id')
    op.drop_table('parent_children')
    op.drop_table('teacher_classes')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('classes')
    op.drop_table('organizations')
    # ### end Alembic commands ###
