"""initial

Revision ID: bfe047c97e6c
Revises: 
Create Date: 2026-07-01 14:18:03.799508

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bfe047c97e6c'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('firmware_versions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('version', sa.String(length=32), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('binary_path', sa.String(length=500), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('version')
    )
    op.create_table('sessions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('course_type', sa.Enum('march', 'car', name='course_type'), nullable=False),
    sa.Column('child_info', sa.JSON(), nullable=True),
    sa.Column('status', sa.Enum('active', 'completed', name='session_status'), nullable=True),
    sa.Column('start_time', sa.DateTime(), nullable=True),
    sa.Column('end_time', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('analysis_results',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('session_id', sa.String(length=36), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('rhythm_sync_rate', sa.Float(), nullable=True),
    sa.Column('freeze_reaction_time', sa.Float(), nullable=True),
    sa.Column('freeze_stability_score', sa.Float(), nullable=True),
    sa.Column('raw_data', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('imu_data',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('session_id', sa.String(length=36), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('accel_x', sa.Float(), nullable=False),
    sa.Column('accel_y', sa.Float(), nullable=False),
    sa.Column('accel_z', sa.Float(), nullable=False),
    sa.Column('gyro_x', sa.Float(), nullable=False),
    sa.Column('gyro_y', sa.Float(), nullable=False),
    sa.Column('gyro_z', sa.Float(), nullable=False),
    sa.Column('device_id', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('reports',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('session_id', sa.String(length=36), nullable=False),
    sa.Column('generated_at', sa.DateTime(), nullable=True),
    sa.Column('content', sa.JSON(), nullable=True),
    sa.Column('status', sa.Enum('pending', 'done', 'failed', name='report_status'), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reports')
    op.drop_table('imu_data')
    op.drop_table('analysis_results')
    op.drop_table('sessions')
    op.drop_table('firmware_versions')
    # ### end Alembic commands ###
